// Re-export all types from shared package
export {
  GlobalRole,
  SpaceType,
  SpaceRole,
  PageStatus,
  type User,
  type Space,
  type Page,
  type PageVersion,
  type Comment,
  type Attachment,
  type Tag,
  type PageTag,
  type Notification,
  type SpacePermission,
  type PagePermission,
  type AuditLog,
  type Webhook,
  type AuthResponse,
  type LoginRequest,
  type RegisterRequest,
  type PaginatedResponse,
  type SearchResult,
} from '@wikso/shared';
