version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '1234:1234'
    env_file: .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
      meilisearch:
        condition: service_started
    networks:
      - wiki-net
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wikso
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wiki-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - wiki-net
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    networks:
      - wiki-net
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - '7700:7700'
    environment:
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meilidata:/meili_data
    networks:
      - wiki-net
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  miniodata:
  meilidata:

networks:
  wiki-net:
    driver: bridge
