/**
 * Strict secret loader.
 *
 * Reads required env vars and refuses to start the app if a secret is missing,
 * obviously a placeholder, or below a minimum entropy threshold. The previous
 * pattern (`process.env.X || 'default-secret'`) silently produced JWTs anyone
 * could forge if the deployer forgot to set the env var.
 *
 * All known placeholder values from the bundled docker-compose.yml are listed
 * here so an operator who forgets to swap them out fails fast at boot rather
 * than shipping a guessable signing key to production.
 */

const KNOWN_PLACEHOLDER_SECRETS = new Set<string>([
  'default-secret',
  'refresh-secret',
  'change-me',
  'change-me-in-production',
  'super-secret-key-change-me-in-production',
  'refresh-secret-change-me-in-production',
]);

export interface RequireSecretOptions {
  /** Minimum byte length. AES-256 / HMAC-SHA256 want >= 32 bytes of entropy. */
  minLength?: number;
}

export function requireSecret(name: string, options: RequireSecretOptions = {}): string {
  const minLength = options.minLength ?? 32;
  const value = process.env[name];

  if (!value || value.trim() === '') {
    throw new Error(
      `[security] Required env var ${name} is not set. Generate a strong random value (e.g. \`openssl rand -hex 32\`) and configure it before starting the app.`,
    );
  }

  if (KNOWN_PLACEHOLDER_SECRETS.has(value)) {
    throw new Error(
      `[security] ${name} is set to a known placeholder value. Replace it with a secret generated by \`openssl rand -hex 32\`. Refusing to start to prevent shipping a guessable signing key.`,
    );
  }

  if (value.length < minLength) {
    throw new Error(
      `[security] ${name} is too short (got ${value.length} chars, need >= ${minLength}). Generate a stronger secret with \`openssl rand -hex 32\`.`,
    );
  }

  return value;
}

/**
 * Best-effort variant for code paths that historically had a fallback. Throws
 * in production, but in dev/test returns the dev fallback (with a warning the
 * first time) so local workflows that never set the env var still boot.
 *
 * Use sparingly — `requireSecret` is preferred for anything that signs tokens
 * or encrypts persistent data.
 */
let warned = false;
export function requireSecretOrDevFallback(
  name: string,
  devFallback: string,
  options: RequireSecretOptions = {},
): string {
  if (process.env.NODE_ENV === 'production') {
    return requireSecret(name, options);
  }
  const value = process.env[name];
  if (value && value.trim() !== '' && !KNOWN_PLACEHOLDER_SECRETS.has(value)) {
    return value;
  }
  if (!warned) {
    // eslint-disable-next-line no-console
    console.warn(
      `[security] ${name} not set or placeholder — using dev fallback. DO NOT deploy this way to production.`,
    );
    warned = true;
  }
  return devFallback;
}
